[package]
name = "input-rs-dioxus-example"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { version = "0.5.6", features = ["web"] }
input-rs = { path = "../../", features = ["dio"] }
dioxus-logger = "0.5.1"
regex = "1.11.1"
